name: NodeJS with Grunt

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: install_emcmake
      run: |
        git clone https://github.com/emscripten-core/emsdk.git 
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest
        source ./emsdk_env.sh
        cd ..
    
    - name: Build
      run: |
        cd binding
        emcmake cmake .
        emmake ninja
        cd ..
        
